### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by hackkhai** [ArtVentureX/comfyui-animatediff#13]
Traceback (most recent call last):
  File "/media/xxxxx/Datasets/Blend/ComfyUI/nodes.py", line 1693, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/media/xxxxx/Datasets/Blend/ComfyUI/custom_nodes/comfyui-animatediff/__init__.py", line 2, in <module>
    from .animatediff.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/media/xxxxx/Datasets/Blend/ComfyUI/custom_nodes/comfyui-animatediff/animatediff/nodes.py", line 17, in <module>
    from comfy.sd import ModelPatcher, calculate_parameters
ImportError: cannot import name 'calculate_parameters' from 'comfy.sd' (/media/xxxxx/Datasets/Blend/ComfyUI/comfy/sd.py)

Cannot import /media/xxxxx/Datasets/Blend/ComfyUI/custom_nodes/comfyui-animatediff module for custom nodes: cannot import name 'calculate_parameters' from 'comfy.sd' (/media/xxxxx/Datasets/Blend/ComfyUI/comfy/sd.py)

Import times for custom nodes:
   0.1 seconds (IMPORT FAILED): /media/xxxxx/Datasets/Blend/ComfyUI/custom_nodes/comfyui-animatediff

**Comment by woshilhz001** [comment]
extension directory-> animatediff -> nodes.py  
Line 16, line 17.
![屏幕截图 2023-08-27 192605](https://github.com/ArtVentureX/comfyui-animatediff/assets/21053332/905695f9-e574-4745-ae77-d6e7966e002f)

**Comment by alexbofa** [comment]
fix `'calculate_parameters' from 'comfy.sd'`: https://github.com/ArtVentureX/comfyui-animatediff/pull/16#issue-1869685207
