### ISSUE TITLE
indexError:list index out of range

### ISSUE THREAD

**Issue by Bearoar** [ArtVentureX/comfyui-animatediff#34]
Hi, Can someone help me with this ：
note：dont have cuda on my navida card, wondering if is this problme. 

bellow is the info :
got prompt
3
[AnimateDiff] - INFO - Injecting motion module with method legacy.
[AnimateDiff] - INFO - Override beta schedule.
loading new
loading in lowvram mode 509.3894233703613
[AnimateDiff] - INFO - Restoring beta schedule.
[AnimateDiff] - INFO - Ejecting motion module with method legacy.
!!! Exception during processing !!!
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff-main\animatediff\nodes.py", line 310, in animatediff_sample
    return super().sample(
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1236, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1206, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 81, in sample
    comfy.model_management.load_models_gpu([model] + models, comfy.model_management.batch_area_memory(noise.shape[0] * noise.shape[2] * noise.shape[3]) + inference_memory)
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 397, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory)
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 290, in model_load
    device_map = accelerate.infer_auto_device_map(self.real_model, max_memory={0: "{}MiB".format(lowvram_model_memory // (1024 * 1024)), "cpu": "16GiB"})
  File "F:\ComfyUI_windows_portable\python_embeded\lib\site-packages\accelerate\utils\modeling.py", line 1033, in infer_auto_device_map
    tied_module_index = [i for i, (n, _) in enumerate(modules_to_treat) if n in tied_param][0]
IndexError: list index out of range

**Comment by artventuredev** [comment]
What video card are you using? Can you share a screenshot of your current workflow?

Also please try to run the same workflow, but swap out the `AnimateDiffSampler` with normal `KSampler`, and update the `batch_size` in the `EmptyLatent` to the save with the `frame_number`. If the same workflow with `KSampler` can run, then you should be able to run with `AnimateDiffSampler`

**Comment by Bearoar** [comment]
![screenshot](https://github.com/ArtVentureX/comfyui-animatediff/assets/46105525/8c5d6995-4b22-4e50-b7d7-ad8b5c6ca19f)
it looks like this , actually, i just drug the 'simple.json' in to the work space, and it give me those error. 

my card is navida k620, haha ,  just wanna to try the work flow,  dont know what is going wrong. 

i tried to change animatediffsampler with ksampler, it works well, when i switch it back, dont work

**Comment by artventuredev** [comment]
When switch to `Ksampler`, please also try with `batch_size` = 16 
<img width="281" alt="image" src="https://github.com/ArtVentureX/comfyui-animatediff/assets/133728487/c1541b7e-3ce0-4a10-a894-1a030b996a95">
