### ISSUE TITLE
TypeError: VanillaTemporalModule.forward() missing 1 required positional argument: 'encoder_hidden_states'

### ISSUE THREAD

**Issue by huweifirst** [ArtVentureX/comfyui-animatediff#42]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff\animatediff\sampler.py", line 295, in animatediff_sample
    return super().sample(
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1236, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1206, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 107, in animatediff_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 97, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 785, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler(), sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 690, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 630, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(sampler_name))(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **extra_options)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\sampling.py", line 137, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 323, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, cond_concat=cond_concat, model_options=model_options, seed=seed)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\external.py", line 125, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\external.py", line 151, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 311, in apply_model
    out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, cond_concat, model_options=model_options, seed=seed)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 289, in sampling_function
    cond, uncond = calc_cond_uncond_batch(model_function, cond, uncond, x, timestep, max_total_area, cond_concat, model_options)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 265, in calc_cond_uncond_batch
    output = model_function(input_x, timestep_, **c).chunk(batch_chunks)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\comfy\model_base.py", line 63, in apply_model
    return self.diffusion_model(xc, t, context=context, y=c_adm, control=control, transformer_options=transformer_options).float()
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL\modules\custom_sdxl_ksampler.py", line 70, in new_unet_forward
    x0 = old_unet_forward(self, x, timesteps, context, y, control, transformer_options, **kwargs)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\custom_nodes\FreeU_Advanced\nodes.py", line 173, in __temp__forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 61, in forward_timestep_embed
    x = layer(x)
  File "D:\SD_Product\Stable\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: VanillaTemporalModule.forward() missing 1 required positional argument: 'encoder_hidden_states'

**Comment by artventuredev** [comment]
I can see you're having both this repo and `AnimateDiff-Evolved`. You shouldn't merge nodes between too repos in the same workflow. Can you share your current workflow?

**Comment by huweifirst** [comment]
https://github.com/ArtVentureX/comfyui-animatediff/tree/main/workflows
[lora.json](https://github.com/ArtVentureX/comfyui-animatediff/blob/main/workflows/lora.json)
I am using this workflow
It cannot be used in the workflows folder

**Comment by artventuredev** [comment]
I have the exact workflow running without any issue.
<img width="1317" alt="image" src="https://github.com/ArtVentureX/comfyui-animatediff/assets/133728487/5c7bf714-068f-407b-b818-ea5dbd184f09">

Please make sure that you have:
- Update this extension to the newest commit
- Either: disable / remove other `AnimateDiff` forks

**Comment by Adam34332** [comment]
> I have the exact workflow running without any issue. <img alt="image" width="1317" src="https://user-images.githubusercontent.com/133728487/272594708-5c7bf714-068f-407b-b818-ea5dbd184f09.png">
> 
> Please make sure that you have:
> 
> * Update this extension to the newest commit
> * Either: disable / remove other `AnimateDiff` forks

I was running normally the day before yesterday, but the same problem occurred when I used it yesterday, 
"Error occurred when executing AnimateDiffSampler:

VanillaTemporalModule.forward() missing 1 required positional argument: 'encoder_hidden_states'"

I also tried to use the process you recommended, in exactly the same form, but this error message was also displayed. I made sure it was the latest update.

**Comment by Adam34332** [comment]
> https://github.com/ArtVentureX/comfyui-animatediff/tree/main/workflows [lora.json](https://github.com/ArtVentureX/comfyui-animatediff/blob/main/workflows/lora.json) I am using this workflow It cannot be used in the workflows folder

I have solved this problem, it is a node conflict. Here is the updated FreeU_Advanced. After I deleted this node, it became normal.

**Comment by artventuredev** [comment]
That's good to hear. I'll test the workflow with FreeU to determine if we can achieve compatibility.

**Comment by huweifirst** [comment]
im try

**Comment by huweifirst** [comment]
[Adam34332](https://github.com/Adam34332) 这个是正确的

**Comment by Adam34332** [comment]
> That's good to hear. I'll test the workflow with FreeU to determine if we can achieve compatibility.

It is not freeU integrated with comfyUi, but an independent plug-in called "FreeU_Advanced".

**Comment by artventuredev** [comment]
@huweifirst @Adam34332, could you please try the latest update? The issue you reported should now be resolved.

Please note that the update also includes modifications to ensure compatibility with the latest version of ComfyUI. If you encounter any errors related to missing modules upon import, updating ComfyUI might help.
