### ISSUE TITLE
(IMPORT FAILED): E:\Stable_Diffusion\ComfyUI\ComfyUI\custom_nodes\comfyui-animatediff

### ISSUE THREAD

**Issue by Sostay** [ArtVentureX/comfyui-animatediff#49]
Ask for help, how should I solve this problem?
————————————————————
Prestartup times for custom nodes:
   0.0 seconds: E:\Stable_Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12288 MB, total RAM 32698 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints E:\SD-webui\models/Stable-diffusion
Adding extra search path configs E:\SD-webui\models/Stable-diffusion
Adding extra search path vae E:\SD-webui\models/VAE
Adding extra search path loras E:\SD-webui\models/Lora
Adding extra search path loras E:\SD-webui\models/LyCORIS
Adding extra search path upscale_models E:\SD-webui\models/ESRGAN
Adding extra search path upscale_models E:\SD-webui\models/RealESRGAN
Adding extra search path upscale_models E:\SD-webui\models/SwinIR
Adding extra search path embeddings E:\SD-webui\embeddings
Adding extra search path hypernetworks E:\SD-webui\models/hypernetworks
Adding extra search path controlnet E:\SD-webui\extensions/sd-webui-controlnet/models
Traceback (most recent call last):
  File "E:\Stable_Diffusion\ComfyUI\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Stable_Diffusion\ComfyUI\ComfyUI\custom_nodes\comfyui-animatediff\__init__.py", line 2, in <module>
    from .animatediff.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\Stable_Diffusion\ComfyUI\ComfyUI\custom_nodes\comfyui-animatediff\animatediff\nodes.py", line 13, in <module>
    from .motion_module import MotionWrapper
  File "E:\Stable_Diffusion\ComfyUI\ComfyUI\custom_nodes\comfyui-animatediff\animatediff\motion_module.py", line 8, in <module>
    from comfy.ldm.modules.attention import (
ImportError: cannot import name 'attention_basic' from 'comfy.ldm.modules.attention' (E:\Stable_Diffusion\ComfyUI\ComfyUI\comfy\ldm\modules\attention.py)

**Comment by Sostay** [comment]
This problem was solved after updating ComfyUI
