### ISSUE TITLE
mixed dtype (CPU): expect parameter to have scalar type of Float

### ISSUE THREAD

**Issue by xi-yang-127** [ArtVentureX/comfyui-animatediff#71]
No matter how you set up the process, AnimateDiffSampler will always pop up the error RuntimeError: mixed dtype (CPU): expect parameter to have scalar type of Float.

The following error reports：
[AnimateDiff] - INFO - Injecting motion module with method default.
Requested to load BaseModel
Loading 1 new model
  0%|                                                                                                                                                                                       | 0/20 [00:00<?, ?it/s]
[AnimateDiff] - INFO - Ejecting motion module with method default.
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/tt/Desktop/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/tt/Desktop/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/tt/Desktop/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/tt/Desktop/ComfyUI/custom_nodes/comfyui-animatediff/animatediff/sampler.py", line 284, in animatediff_sample
    return super().sample(
  File "/home/tt/Desktop/ComfyUI/nodes.py", line 1286, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/home/tt/Desktop/ComfyUI/nodes.py", line 1256, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/home/tt/Desktop/ComfyUI/comfy/sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/tt/Desktop/ComfyUI/comfy/samplers.py", line 711, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/tt/Desktop/ComfyUI/comfy/samplers.py", line 617, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/home/tt/Desktop/ComfyUI/comfy/samplers.py", line 556, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/home/tt/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/tt/Desktop/ComfyUI/comfy/k_diffusion/sampling.py", line 137, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/home/tt/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tt/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tt/Desktop/ComfyUI/comfy/samplers.py", line 277, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
  File "/home/tt/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tt/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tt/Desktop/ComfyUI/comfy/samplers.py", line 267, in forward
    return self.apply_model(*args, **kwargs)
  File "/home/tt/Desktop/ComfyUI/comfy/samplers.py", line 264, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "/home/tt/Desktop/ComfyUI/comfy/samplers.py", line 252, in sampling_function
    cond, uncond = calc_cond_uncond_batch(model, cond, uncond, x, timestep, model_options)
  File "/home/tt/Desktop/ComfyUI/comfy/samplers.py", line 230, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/home/tt/Desktop/ComfyUI/comfy/model_base.py", line 68, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/home/tt/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tt/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tt/Desktop/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 619, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options)
  File "/home/tt/Desktop/ComfyUI/custom_nodes/comfyui-animatediff/animatediff/sampler.py", line 31, in forward_timestep_embed
    x = layer(x, context)
  File "/home/tt/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tt/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tt/Desktop/ComfyUI/custom_nodes/comfyui-animatediff/animatediff/motion_module.py", line 183, in forward
    return self.temporal_transformer(input_tensor, encoder_hidden_states, attention_mask)
  File "/home/tt/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tt/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tt/Desktop/ComfyUI/custom_nodes/comfyui-animatediff/animatediff/motion_module.py", line 244, in forward
    hidden_states = self.norm(hidden_states)
  File "/home/tt/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tt/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tt/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/normalization.py", line 279, in forward
    return F.group_norm(
  File "/home/tt/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/functional.py", line 2558, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: mixed dtype (CPU): expect parameter to have scalar type of Float

**Comment by xi-yang-127** [comment]
This is my workflow:
[workflow_Animate.json](https://github.com/ArtVentureX/comfyui-animatediff/files/13445704/workflow_Animate.json)

**Comment by artventuredev** [comment]
Please try this workflow [simple-lcm.json](https://github.com/ArtVentureX/comfyui-animatediff/files/13452930/simple-lcm.1.json).

Seems like the `LoadCheckpointWithConfig` cause the issue. I also removed the `ModelSamplingDiscrecte`.

<img width="1268" alt="image" src="https://github.com/ArtVentureX/comfyui-animatediff/assets/133728487/1872d94b-c447-40ad-a5ab-00d31f9e4269">
