### ISSUE TITLE
[import failed]conflict with other node

### ISSUE THREAD

**Issue by weykon** [ArtVentureX/comfyui-animatediff#78]
![image](https://github.com/ArtVentureX/comfyui-animatediff/assets/36456814/9a9eccdf-8510-4b61-9e00-ed5055c6617b)

![image](https://github.com/ArtVentureX/comfyui-animatediff/assets/36456814/99a52d11-e6cb-4819-ad76-baf70e22ad9b)

I'm novice at comfyui, can anybody help me, the last node is undefined.

it maybe Video Combine Node. 

it said conflict with other node, but I had not installed that.

I already put the file `mm_sd_v15.ckpt`,`mm_sd_v15_v2.ckpt`,`mm_sd_v14.ckpt` in ./custom_nodes/comfyui-animatediff/models

**Comment by weykon** [comment]
```shell
Traceback (most recent call last):
  File "/Volumes/ModelY/Y-gitProject/ComfyUI/nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Volumes/ModelY/Y-gitProject/ComfyUI/custom_nodes/comfyui-animatediff/__init__.py", line 2, in <module>
    from .animatediff.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/Volumes/ModelY/Y-gitProject/ComfyUI/custom_nodes/comfyui-animatediff/animatediff/nodes.py", line 16, in <module>
    from .sampler import AnimateDiffSampler, AnimateDiffSlidingWindowOptions
  File "/Volumes/ModelY/Y-gitProject/ComfyUI/custom_nodes/comfyui-animatediff/animatediff/sampler.py", line 12, in <module>
    from .sliding_schedule import ContextSchedules
  File "/Volumes/ModelY/Y-gitProject/ComfyUI/custom_nodes/comfyui-animatediff/animatediff/sliding_schedule.py", line 147
    match name:
          ^
SyntaxError: invalid syntax

Cannot import /Volumes/ModelY/Y-gitProject/ComfyUI/custom_nodes/comfyui-animatediff module for custom nodes: invalid syntax (sliding_schedule.py, line 147)

Import times for custom nodes:
   0.0 seconds: /Volumes/ModelY/Y-gitProject/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
   0.0 seconds (IMPORT FAILED): /Volumes/ModelY/Y-gitProject/ComfyUI/custom_nodes/comfyui-animatediff
   0.3 seconds: /Volumes/ModelY/Y-gitProject/ComfyUI/custom_nodes/ComfyUI-Manager
   
```

I found some explicit error info

**Comment by weykon** [comment]
I found the 3.9 version of python not support advance writing at `match pattern`.  
I already fixed it by myself, and I upraise a PR. please check.
[PR 79](https://github.com/ArtVentureX/comfyui-animatediff/pull/79)

**Comment by artventuredev** [comment]
Thank you for the PR. Merged!
